name: CI/CD inocam_client to AWS S3

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: AWS IAM 사용자 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  

      - name: Setting .env
        run: |
          echo "GENERATE_SOURCEMAP=${{ secrets.GENERATE_SOURCEMAP }}" >> .env
          echo "REACT_APP_SERVER_KEY=${{ secrets.REACT_APP_SERVER_KEY }}" >> .env
          echo "REACT_APP_REST_API=${{ secrets.REACT_APP_REST_API }}" >> .env
          echo "REACT_APP_REDIRECT_URL=${{ secrets.REACT_APP_REDIRECT_URL }}" >> .env
          cat .env
          
      - name: Build
        run: |
          npm install -g yarn
          yarn install --immutable
          yarn build    
        
      - name: Deploy to S3 bucket
        run: |
          aws s3 sync build/ s3://inocamfinal